# Generated by iptables-save v1.8.9 (nf_tables) on Sun Apr  7 01:07:02 2024
*filter
:INPUT DROP [4948:548363]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [646240:298902919]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 25565 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 7777 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 10000 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 30120 -j ACCEPT
-A INPUT -p udp -m udp --dport 30120 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 40120 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3009 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3000 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 44955 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1410 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2812 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 44966 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 25555 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 19132 -j ACCEPT
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 3000 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Sun Apr  7 01:07:02 2024
# Generated by iptables-save v1.8.9 (nf_tables) on Sun Apr  7 01:07:02 2024
*nat
:PREROUTING ACCEPT [26696:4454293]
:INPUT ACCEPT [448:23624]
:OUTPUT ACCEPT [4590:283532]
:POSTROUTING ACCEPT [4590:283532]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 3000 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 3009 -j DNAT --to-destination 172.17.0.2:3000
COMMIT
# Completed on Sun Apr  7 01:07:02 2024
